/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package era.foss.model.core.rif.provider;

import era.foss.model.core.rif.util.RifAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class RifItemProviderAdapterFactory extends RifAdapterFactory implements
		ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RifItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPoliciesItemProvider accessPoliciesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPoliciesAdapter() {
		if (accessPoliciesItemProvider == null) {
			accessPoliciesItemProvider = new AccessPoliciesItemProvider(this);
		}

		return accessPoliciesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicyItemProvider accessPolicyItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicyAdapter() {
		if (accessPolicyItemProvider == null) {
			accessPolicyItemProvider = new AccessPolicyItemProvider(this);
		}

		return accessPolicyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionComplex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionComplexItemProvider attributeDefinitionComplexItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionComplex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionComplexAdapter() {
		if (attributeDefinitionComplexItemProvider == null) {
			attributeDefinitionComplexItemProvider = new AttributeDefinitionComplexItemProvider(
					this);
		}

		return attributeDefinitionComplexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionEnumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionEnumerationItemProvider attributeDefinitionEnumerationItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionEnumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionEnumerationAdapter() {
		if (attributeDefinitionEnumerationItemProvider == null) {
			attributeDefinitionEnumerationItemProvider = new AttributeDefinitionEnumerationItemProvider(
					this);
		}

		return attributeDefinitionEnumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionSimple} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionSimpleItemProvider attributeDefinitionSimpleItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionSimple}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionSimpleAdapter() {
		if (attributeDefinitionSimpleItemProvider == null) {
			attributeDefinitionSimpleItemProvider = new AttributeDefinitionSimpleItemProvider(
					this);
		}

		return attributeDefinitionSimpleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionsItemProvider attributeDefinitionsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionsAdapter() {
		if (attributeDefinitionsItemProvider == null) {
			attributeDefinitionsItemProvider = new AttributeDefinitionsItemProvider(
					this);
		}

		return attributeDefinitionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEmbeddedDocument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEmbeddedDocumentItemProvider attributeValueEmbeddedDocumentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEmbeddedDocument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEmbeddedDocumentAdapter() {
		if (attributeValueEmbeddedDocumentItemProvider == null) {
			attributeValueEmbeddedDocumentItemProvider = new AttributeValueEmbeddedDocumentItemProvider(
					this);
		}

		return attributeValueEmbeddedDocumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEmbeddedFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEmbeddedFileItemProvider attributeValueEmbeddedFileItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEmbeddedFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEmbeddedFileAdapter() {
		if (attributeValueEmbeddedFileItemProvider == null) {
			attributeValueEmbeddedFileItemProvider = new AttributeValueEmbeddedFileItemProvider(
					this);
		}

		return attributeValueEmbeddedFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEnumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEnumerationItemProvider attributeValueEnumerationItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEnumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEnumerationAdapter() {
		if (attributeValueEnumerationItemProvider == null) {
			attributeValueEnumerationItemProvider = new AttributeValueEnumerationItemProvider(
					this);
		}

		return attributeValueEnumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueFileReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueFileReferenceItemProvider attributeValueFileReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueFileReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueFileReferenceAdapter() {
		if (attributeValueFileReferenceItemProvider == null) {
			attributeValueFileReferenceItemProvider = new AttributeValueFileReferenceItemProvider(
					this);
		}

		return attributeValueFileReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueSimple} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueSimpleItemProvider attributeValueSimpleItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueSimple}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueSimpleAdapter() {
		if (attributeValueSimpleItemProvider == null) {
			attributeValueSimpleItemProvider = new AttributeValueSimpleItemProvider(
					this);
		}

		return attributeValueSimpleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValuesItemProvider attributeValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValuesAdapter() {
		if (attributeValuesItemProvider == null) {
			attributeValuesItemProvider = new AttributeValuesItemProvider(this);
		}

		return attributeValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueXmlData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueXmlDataItemProvider attributeValueXmlDataItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueXmlData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueXmlDataAdapter() {
		if (attributeValueXmlDataItemProvider == null) {
			attributeValueXmlDataItemProvider = new AttributeValueXmlDataItemProvider(
					this);
		}

		return attributeValueXmlDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.BinaryContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BinaryContentItemProvider binaryContentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.BinaryContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBinaryContentAdapter() {
		if (binaryContentItemProvider == null) {
			binaryContentItemProvider = new BinaryContentItemProvider(this);
		}

		return binaryContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEmbeddedFileBinaryContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEmbeddedFileBinaryContentItemProvider attributeValueEmbeddedFileBinaryContentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEmbeddedFileBinaryContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEmbeddedFileBinaryContentAdapter() {
		if (attributeValueEmbeddedFileBinaryContentItemProvider == null) {
			attributeValueEmbeddedFileBinaryContentItemProvider = new AttributeValueEmbeddedFileBinaryContentItemProvider(
					this);
		}

		return attributeValueEmbeddedFileBinaryContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchyChildren} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchyChildrenItemProvider specHierarchyChildrenItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchyChildren}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchyChildrenAdapter() {
		if (specHierarchyChildrenItemProvider == null) {
			specHierarchyChildrenItemProvider = new SpecHierarchyChildrenItemProvider(
					this);
		}

		return specHierarchyChildrenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchyRootChildren} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchyRootChildrenItemProvider specHierarchyRootChildrenItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchyRootChildren}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchyRootChildrenAdapter() {
		if (specHierarchyRootChildrenItemProvider == null) {
			specHierarchyRootChildrenItemProvider = new SpecHierarchyRootChildrenItemProvider(
					this);
		}

		return specHierarchyRootChildrenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionBinaryFile} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionBinaryFileItemProvider datatypeDefinitionBinaryFileItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionBinaryFile}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionBinaryFileAdapter() {
		if (datatypeDefinitionBinaryFileItemProvider == null) {
			datatypeDefinitionBinaryFileItemProvider = new DatatypeDefinitionBinaryFileItemProvider(
					this);
		}

		return datatypeDefinitionBinaryFileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionBoolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionBooleanItemProvider datatypeDefinitionBooleanItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionBoolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionBooleanAdapter() {
		if (datatypeDefinitionBooleanItemProvider == null) {
			datatypeDefinitionBooleanItemProvider = new DatatypeDefinitionBooleanItemProvider(
					this);
		}

		return datatypeDefinitionBooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionDocument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionDocumentItemProvider datatypeDefinitionDocumentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionDocument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionDocumentAdapter() {
		if (datatypeDefinitionDocumentItemProvider == null) {
			datatypeDefinitionDocumentItemProvider = new DatatypeDefinitionDocumentItemProvider(
					this);
		}

		return datatypeDefinitionDocumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionEnumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionEnumerationItemProvider datatypeDefinitionEnumerationItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionEnumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionEnumerationAdapter() {
		if (datatypeDefinitionEnumerationItemProvider == null) {
			datatypeDefinitionEnumerationItemProvider = new DatatypeDefinitionEnumerationItemProvider(
					this);
		}

		return datatypeDefinitionEnumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionInteger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionIntegerItemProvider datatypeDefinitionIntegerItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionInteger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionIntegerAdapter() {
		if (datatypeDefinitionIntegerItemProvider == null) {
			datatypeDefinitionIntegerItemProvider = new DatatypeDefinitionIntegerItemProvider(
					this);
		}

		return datatypeDefinitionIntegerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionReal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionRealItemProvider datatypeDefinitionRealItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionReal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionRealAdapter() {
		if (datatypeDefinitionRealItemProvider == null) {
			datatypeDefinitionRealItemProvider = new DatatypeDefinitionRealItemProvider(
					this);
		}

		return datatypeDefinitionRealItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionString} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionStringItemProvider datatypeDefinitionStringItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionStringAdapter() {
		if (datatypeDefinitionStringItemProvider == null) {
			datatypeDefinitionStringItemProvider = new DatatypeDefinitionStringItemProvider(
					this);
		}

		return datatypeDefinitionStringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionsItemProvider datatypeDefinitionsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionsAdapter() {
		if (datatypeDefinitionsItemProvider == null) {
			datatypeDefinitionsItemProvider = new DatatypeDefinitionsItemProvider(
					this);
		}

		return datatypeDefinitionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DatatypeDefinitionXmlData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypeDefinitionXmlDataItemProvider datatypeDefinitionXmlDataItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DatatypeDefinitionXmlData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypeDefinitionXmlDataAdapter() {
		if (datatypeDefinitionXmlDataItemProvider == null) {
			datatypeDefinitionXmlDataItemProvider = new DatatypeDefinitionXmlDataItemProvider(
					this);
		}

		return datatypeDefinitionXmlDataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.Datatypes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatatypesItemProvider datatypesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.Datatypes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatatypesAdapter() {
		if (datatypesItemProvider == null) {
			datatypesItemProvider = new DatatypesItemProvider(this);
		}

		return datatypesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DefaultValue2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultValue2ItemProvider defaultValue2ItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DefaultValue2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultValue2Adapter() {
		if (defaultValue2ItemProvider == null) {
			defaultValue2ItemProvider = new DefaultValue2ItemProvider(this);
		}

		return defaultValue2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DefaultValue3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultValue3ItemProvider defaultValue3ItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DefaultValue3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultValue3Adapter() {
		if (defaultValue3ItemProvider == null) {
			defaultValue3ItemProvider = new DefaultValue3ItemProvider(this);
		}

		return defaultValue3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DefaultValue4} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultValue4ItemProvider defaultValue4ItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DefaultValue4}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultValue4Adapter() {
		if (defaultValue4ItemProvider == null) {
			defaultValue4ItemProvider = new DefaultValue4ItemProvider(this);
		}

		return defaultValue4ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionSimpleDefaultValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionSimpleDefaultValueItemProvider attributeDefinitionSimpleDefaultValueItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionSimpleDefaultValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionSimpleDefaultValueAdapter() {
		if (attributeDefinitionSimpleDefaultValueItemProvider == null) {
			attributeDefinitionSimpleDefaultValueItemProvider = new AttributeDefinitionSimpleDefaultValueItemProvider(
					this);
		}

		return attributeDefinitionSimpleDefaultValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionEnumerationDefaultValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionEnumerationDefaultValueItemProvider attributeDefinitionEnumerationDefaultValueItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionEnumerationDefaultValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionEnumerationDefaultValueAdapter() {
		if (attributeDefinitionEnumerationDefaultValueItemProvider == null) {
			attributeDefinitionEnumerationDefaultValueItemProvider = new AttributeDefinitionEnumerationDefaultValueItemProvider(
					this);
		}

		return attributeDefinitionEnumerationDefaultValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionComplexDefaultValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionComplexDefaultValueItemProvider attributeDefinitionComplexDefaultValueItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionComplexDefaultValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionComplexDefaultValueAdapter() {
		if (attributeDefinitionComplexDefaultValueItemProvider == null) {
			attributeDefinitionComplexDefaultValueItemProvider = new AttributeDefinitionComplexDefaultValueItemProvider(
					this);
		}

		return attributeDefinitionComplexDefaultValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEmbeddedDocumentDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEmbeddedDocumentDefinitionItemProvider attributeValueEmbeddedDocumentDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEmbeddedDocumentDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEmbeddedDocumentDefinitionAdapter() {
		if (attributeValueEmbeddedDocumentDefinitionItemProvider == null) {
			attributeValueEmbeddedDocumentDefinitionItemProvider = new AttributeValueEmbeddedDocumentDefinitionItemProvider(
					this);
		}

		return attributeValueEmbeddedDocumentDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueFileReferenceDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueFileReferenceDefinitionItemProvider attributeValueFileReferenceDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueFileReferenceDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueFileReferenceDefinitionAdapter() {
		if (attributeValueFileReferenceDefinitionItemProvider == null) {
			attributeValueFileReferenceDefinitionItemProvider = new AttributeValueFileReferenceDefinitionItemProvider(
					this);
		}

		return attributeValueFileReferenceDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEmbeddedFileDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEmbeddedFileDefinitionItemProvider attributeValueEmbeddedFileDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEmbeddedFileDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEmbeddedFileDefinitionAdapter() {
		if (attributeValueEmbeddedFileDefinitionItemProvider == null) {
			attributeValueEmbeddedFileDefinitionItemProvider = new AttributeValueEmbeddedFileDefinitionItemProvider(
					this);
		}

		return attributeValueEmbeddedFileDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueSimpleDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueSimpleDefinitionItemProvider attributeValueSimpleDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueSimpleDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueSimpleDefinitionAdapter() {
		if (attributeValueSimpleDefinitionItemProvider == null) {
			attributeValueSimpleDefinitionItemProvider = new AttributeValueSimpleDefinitionItemProvider(
					this);
		}

		return attributeValueSimpleDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEnumerationDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEnumerationDefinitionItemProvider attributeValueEnumerationDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEnumerationDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEnumerationDefinitionAdapter() {
		if (attributeValueEnumerationDefinitionItemProvider == null) {
			attributeValueEnumerationDefinitionItemProvider = new AttributeValueEnumerationDefinitionItemProvider(
					this);
		}

		return attributeValueEnumerationDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueXmlDataDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueXmlDataDefinitionItemProvider attributeValueXmlDataDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueXmlDataDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueXmlDataDefinitionAdapter() {
		if (attributeValueXmlDataDefinitionItemProvider == null) {
			attributeValueXmlDataDefinitionItemProvider = new AttributeValueXmlDataDefinitionItemProvider(
					this);
		}

		return attributeValueXmlDataDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.EmbeddedValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmbeddedValueItemProvider embeddedValueItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.EmbeddedValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmbeddedValueAdapter() {
		if (embeddedValueItemProvider == null) {
			embeddedValueItemProvider = new EmbeddedValueItemProvider(this);
		}

		return embeddedValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.EnumValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumValueItemProvider enumValueItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.EnumValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumValueAdapter() {
		if (enumValueItemProvider == null) {
			enumValueItemProvider = new EnumValueItemProvider(this);
		}

		return enumValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.Object} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectItemProvider objectItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.Object}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectAdapter() {
		if (objectItemProvider == null) {
			objectItemProvider = new ObjectItemProvider(this);
		}

		return objectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.Properties} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertiesItemProvider propertiesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.Properties}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertiesAdapter() {
		if (propertiesItemProvider == null) {
			propertiesItemProvider = new PropertiesItemProvider(this);
		}

		return propertiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecGroupRelationGroups} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecGroupRelationGroupsItemProvider specGroupRelationGroupsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecGroupRelationGroups}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecGroupRelationGroupsAdapter() {
		if (specGroupRelationGroupsItemProvider == null) {
			specGroupRelationGroupsItemProvider = new SpecGroupRelationGroupsItemProvider(
					this);
		}

		return specGroupRelationGroupsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicyRelationGroups} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicyRelationGroupsItemProvider accessPolicyRelationGroupsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicyRelationGroups}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicyRelationGroupsAdapter() {
		if (accessPolicyRelationGroupsItemProvider == null) {
			accessPolicyRelationGroupsItemProvider = new AccessPolicyRelationGroupsItemProvider(
					this);
		}

		return accessPolicyRelationGroupsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RelationGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationGroupItemProvider relationGroupItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RelationGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationGroupAdapter() {
		if (relationGroupItemProvider == null) {
			relationGroupItemProvider = new RelationGroupItemProvider(this);
		}

		return relationGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RelationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationTypeItemProvider relationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RelationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationTypeAdapter() {
		if (relationTypeItemProvider == null) {
			relationTypeItemProvider = new RelationTypeItemProvider(this);
		}

		return relationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.Rif} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RifItemProvider rifItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.Rif}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRifAdapter() {
		if (rifItemProvider == null) {
			rifItemProvider = new RifItemProvider(this);
		}

		return rifItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.Source} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SourceItemProvider sourceItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.Source}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSourceAdapter() {
		if (sourceItemProvider == null) {
			sourceItemProvider = new SourceItemProvider(this);
		}

		return sourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecAttributes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecAttributesItemProvider specAttributesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecAttributes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecAttributesAdapter() {
		if (specAttributesItemProvider == null) {
			specAttributesItemProvider = new SpecAttributesItemProvider(this);
		}

		return specAttributesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RifSpecGroups} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RifSpecGroupsItemProvider rifSpecGroupsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RifSpecGroups}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRifSpecGroupsAdapter() {
		if (rifSpecGroupsItemProvider == null) {
			rifSpecGroupsItemProvider = new RifSpecGroupsItemProvider(this);
		}

		return rifSpecGroupsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicySpecGroups} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicySpecGroupsItemProvider accessPolicySpecGroupsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicySpecGroups}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicySpecGroupsAdapter() {
		if (accessPolicySpecGroupsItemProvider == null) {
			accessPolicySpecGroupsItemProvider = new AccessPolicySpecGroupsItemProvider(
					this);
		}

		return accessPolicySpecGroupsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecGroupItemProvider specGroupItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecGroupAdapter() {
		if (specGroupItemProvider == null) {
			specGroupItemProvider = new SpecGroupItemProvider(this);
		}

		return specGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchiesItemProvider specHierarchiesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchiesAdapter() {
		if (specHierarchiesItemProvider == null) {
			specHierarchiesItemProvider = new SpecHierarchiesItemProvider(this);
		}

		return specHierarchiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RifSpecHierarchyRoots} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RifSpecHierarchyRootsItemProvider rifSpecHierarchyRootsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RifSpecHierarchyRoots}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRifSpecHierarchyRootsAdapter() {
		if (rifSpecHierarchyRootsItemProvider == null) {
			rifSpecHierarchyRootsItemProvider = new RifSpecHierarchyRootsItemProvider(
					this);
		}

		return rifSpecHierarchyRootsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicySpecHierarchyRoots} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicySpecHierarchyRootsItemProvider accessPolicySpecHierarchyRootsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicySpecHierarchyRoots}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicySpecHierarchyRootsAdapter() {
		if (accessPolicySpecHierarchyRootsItemProvider == null) {
			accessPolicySpecHierarchyRootsItemProvider = new AccessPolicySpecHierarchyRootsItemProvider(
					this);
		}

		return accessPolicySpecHierarchyRootsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchyRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchyRootItemProvider specHierarchyRootItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchyRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchyRootAdapter() {
		if (specHierarchyRootItemProvider == null) {
			specHierarchyRootItemProvider = new SpecHierarchyRootItemProvider(
					this);
		}

		return specHierarchyRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchyItemProvider specHierarchyItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchyAdapter() {
		if (specHierarchyItemProvider == null) {
			specHierarchyItemProvider = new SpecHierarchyItemProvider(this);
		}

		return specHierarchyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecifiedValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecifiedValuesItemProvider specifiedValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecifiedValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecifiedValuesAdapter() {
		if (specifiedValuesItemProvider == null) {
			specifiedValuesItemProvider = new SpecifiedValuesItemProvider(this);
		}

		return specifiedValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecGroupSpecObjects} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecGroupSpecObjectsItemProvider specGroupSpecObjectsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecGroupSpecObjects}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecGroupSpecObjectsAdapter() {
		if (specGroupSpecObjectsItemProvider == null) {
			specGroupSpecObjectsItemProvider = new SpecGroupSpecObjectsItemProvider(
					this);
		}

		return specGroupSpecObjectsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RifSpecObjects} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RifSpecObjectsItemProvider rifSpecObjectsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RifSpecObjects}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRifSpecObjectsAdapter() {
		if (rifSpecObjectsItemProvider == null) {
			rifSpecObjectsItemProvider = new RifSpecObjectsItemProvider(this);
		}

		return rifSpecObjectsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicySpecObjects} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicySpecObjectsItemProvider accessPolicySpecObjectsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicySpecObjects}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicySpecObjectsAdapter() {
		if (accessPolicySpecObjectsItemProvider == null) {
			accessPolicySpecObjectsItemProvider = new AccessPolicySpecObjectsItemProvider(
					this);
		}

		return accessPolicySpecObjectsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecObjectItemProvider specObjectItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecObjectAdapter() {
		if (specObjectItemProvider == null) {
			specObjectItemProvider = new SpecObjectItemProvider(this);
		}

		return specObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RifSpecRelations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RifSpecRelationsItemProvider rifSpecRelationsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RifSpecRelations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRifSpecRelationsAdapter() {
		if (rifSpecRelationsItemProvider == null) {
			rifSpecRelationsItemProvider = new RifSpecRelationsItemProvider(
					this);
		}

		return rifSpecRelationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RelationGroupSpecRelations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationGroupSpecRelationsItemProvider relationGroupSpecRelationsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RelationGroupSpecRelations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationGroupSpecRelationsAdapter() {
		if (relationGroupSpecRelationsItemProvider == null) {
			relationGroupSpecRelationsItemProvider = new RelationGroupSpecRelationsItemProvider(
					this);
		}

		return relationGroupSpecRelationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicySpecRelations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicySpecRelationsItemProvider accessPolicySpecRelationsItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicySpecRelations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicySpecRelationsAdapter() {
		if (accessPolicySpecRelationsItemProvider == null) {
			accessPolicySpecRelationsItemProvider = new AccessPolicySpecRelationsItemProvider(
					this);
		}

		return accessPolicySpecRelationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecRelation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecRelationItemProvider specRelationItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecRelation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecRelationAdapter() {
		if (specRelationItemProvider == null) {
			specRelationItemProvider = new SpecRelationItemProvider(this);
		}

		return specRelationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.RifSpecTypes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RifSpecTypesItemProvider rifSpecTypesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.RifSpecTypes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRifSpecTypesAdapter() {
		if (rifSpecTypesItemProvider == null) {
			rifSpecTypesItemProvider = new RifSpecTypesItemProvider(this);
		}

		return rifSpecTypesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AccessPolicySpecTypes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessPolicySpecTypesItemProvider accessPolicySpecTypesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AccessPolicySpecTypes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessPolicySpecTypesAdapter() {
		if (accessPolicySpecTypesItemProvider == null) {
			accessPolicySpecTypesItemProvider = new AccessPolicySpecTypesItemProvider(
					this);
		}

		return accessPolicySpecTypesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecTypeItemProvider specTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecTypeAdapter() {
		if (specTypeItemProvider == null) {
			specTypeItemProvider = new SpecTypeItemProvider(this);
		}

		return specTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.TargetGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetGroupItemProvider targetGroupItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.TargetGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetGroupAdapter() {
		if (targetGroupItemProvider == null) {
			targetGroupItemProvider = new TargetGroupItemProvider(this);
		}

		return targetGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.Target} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetItemProvider targetItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.Target}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetAdapter() {
		if (targetItemProvider == null) {
			targetItemProvider = new TargetItemProvider(this);
		}

		return targetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionSimpleType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionSimpleTypeItemProvider attributeDefinitionSimpleTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionSimpleType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionSimpleTypeAdapter() {
		if (attributeDefinitionSimpleTypeItemProvider == null) {
			attributeDefinitionSimpleTypeItemProvider = new AttributeDefinitionSimpleTypeItemProvider(
					this);
		}

		return attributeDefinitionSimpleTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecRelationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecRelationTypeItemProvider specRelationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecRelationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecRelationTypeAdapter() {
		if (specRelationTypeItemProvider == null) {
			specRelationTypeItemProvider = new SpecRelationTypeItemProvider(
					this);
		}

		return specRelationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionEnumerationType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionEnumerationTypeItemProvider attributeDefinitionEnumerationTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionEnumerationType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionEnumerationTypeAdapter() {
		if (attributeDefinitionEnumerationTypeItemProvider == null) {
			attributeDefinitionEnumerationTypeItemProvider = new AttributeDefinitionEnumerationTypeItemProvider(
					this);
		}

		return attributeDefinitionEnumerationTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecObjectType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecObjectTypeItemProvider specObjectTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecObjectType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecObjectTypeAdapter() {
		if (specObjectTypeItemProvider == null) {
			specObjectTypeItemProvider = new SpecObjectTypeItemProvider(this);
		}

		return specObjectTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchyRootType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchyRootTypeItemProvider specHierarchyRootTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchyRootType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchyRootTypeAdapter() {
		if (specHierarchyRootTypeItemProvider == null) {
			specHierarchyRootTypeItemProvider = new SpecHierarchyRootTypeItemProvider(
					this);
		}

		return specHierarchyRootTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecGroupType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecGroupTypeItemProvider specGroupTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecGroupType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecGroupTypeAdapter() {
		if (specGroupTypeItemProvider == null) {
			specGroupTypeItemProvider = new SpecGroupTypeItemProvider(this);
		}

		return specGroupTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeDefinitionComplexType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDefinitionComplexTypeItemProvider attributeDefinitionComplexTypeItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeDefinitionComplexType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDefinitionComplexTypeAdapter() {
		if (attributeDefinitionComplexTypeItemProvider == null) {
			attributeDefinitionComplexTypeItemProvider = new AttributeDefinitionComplexTypeItemProvider(
					this);
		}

		return attributeDefinitionComplexTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecObjectValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecObjectValuesItemProvider specObjectValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecObjectValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecObjectValuesAdapter() {
		if (specObjectValuesItemProvider == null) {
			specObjectValuesItemProvider = new SpecObjectValuesItemProvider(
					this);
		}

		return specObjectValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecRelationValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecRelationValuesItemProvider specRelationValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecRelationValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecRelationValuesAdapter() {
		if (specRelationValuesItemProvider == null) {
			specRelationValuesItemProvider = new SpecRelationValuesItemProvider(
					this);
		}

		return specRelationValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecGroupValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecGroupValuesItemProvider specGroupValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecGroupValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecGroupValuesAdapter() {
		if (specGroupValuesItemProvider == null) {
			specGroupValuesItemProvider = new SpecGroupValuesItemProvider(this);
		}

		return specGroupValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.SpecHierarchyRootValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecHierarchyRootValuesItemProvider specHierarchyRootValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.SpecHierarchyRootValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecHierarchyRootValuesAdapter() {
		if (specHierarchyRootValuesItemProvider == null) {
			specHierarchyRootValuesItemProvider = new SpecHierarchyRootValuesItemProvider(
					this);
		}

		return specHierarchyRootValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEnumerationValues} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEnumerationValuesItemProvider attributeValueEnumerationValuesItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEnumerationValues}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEnumerationValuesAdapter() {
		if (attributeValueEnumerationValuesItemProvider == null) {
			attributeValueEnumerationValuesItemProvider = new AttributeValueEnumerationValuesItemProvider(
					this);
		}

		return attributeValueEnumerationValuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.XhtmlContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XhtmlContentItemProvider xhtmlContentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.XhtmlContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXhtmlContentAdapter() {
		if (xhtmlContentItemProvider == null) {
			xhtmlContentItemProvider = new XhtmlContentItemProvider(this);
		}

		return xhtmlContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueEmbeddedDocumentXhtmlContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueEmbeddedDocumentXhtmlContentItemProvider attributeValueEmbeddedDocumentXhtmlContentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueEmbeddedDocumentXhtmlContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueEmbeddedDocumentXhtmlContentAdapter() {
		if (attributeValueEmbeddedDocumentXhtmlContentItemProvider == null) {
			attributeValueEmbeddedDocumentXhtmlContentItemProvider = new AttributeValueEmbeddedDocumentXhtmlContentItemProvider(
					this);
		}

		return attributeValueEmbeddedDocumentXhtmlContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.XmlContentXmlContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XmlContentXmlContentItemProvider xmlContentXmlContentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.XmlContentXmlContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createXmlContentXmlContentAdapter() {
		if (xmlContentXmlContentItemProvider == null) {
			xmlContentXmlContentItemProvider = new XmlContentXmlContentItemProvider(
					this);
		}

		return xmlContentXmlContentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link era.foss.model.core.rif.AttributeValueXmlDataXmlContent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeValueXmlDataXmlContentItemProvider attributeValueXmlDataXmlContentItemProvider;

	/**
	 * This creates an adapter for a {@link era.foss.model.core.rif.AttributeValueXmlDataXmlContent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeValueXmlDataXmlContentAdapter() {
		if (attributeValueXmlDataXmlContentItemProvider == null) {
			attributeValueXmlDataXmlContentItemProvider = new AttributeValueXmlDataXmlContentItemProvider(
					this);
		}

		return attributeValueXmlDataXmlContentItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory
				.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(
			ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class)
					|| (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (accessPoliciesItemProvider != null)
			accessPoliciesItemProvider.dispose();
		if (accessPolicyItemProvider != null)
			accessPolicyItemProvider.dispose();
		if (attributeDefinitionComplexItemProvider != null)
			attributeDefinitionComplexItemProvider.dispose();
		if (attributeDefinitionEnumerationItemProvider != null)
			attributeDefinitionEnumerationItemProvider.dispose();
		if (attributeDefinitionSimpleItemProvider != null)
			attributeDefinitionSimpleItemProvider.dispose();
		if (attributeDefinitionsItemProvider != null)
			attributeDefinitionsItemProvider.dispose();
		if (attributeValueEmbeddedDocumentItemProvider != null)
			attributeValueEmbeddedDocumentItemProvider.dispose();
		if (attributeValueEmbeddedFileItemProvider != null)
			attributeValueEmbeddedFileItemProvider.dispose();
		if (attributeValueEnumerationItemProvider != null)
			attributeValueEnumerationItemProvider.dispose();
		if (attributeValueFileReferenceItemProvider != null)
			attributeValueFileReferenceItemProvider.dispose();
		if (attributeValueSimpleItemProvider != null)
			attributeValueSimpleItemProvider.dispose();
		if (attributeValuesItemProvider != null)
			attributeValuesItemProvider.dispose();
		if (attributeValueXmlDataItemProvider != null)
			attributeValueXmlDataItemProvider.dispose();
		if (binaryContentItemProvider != null)
			binaryContentItemProvider.dispose();
		if (attributeValueEmbeddedFileBinaryContentItemProvider != null)
			attributeValueEmbeddedFileBinaryContentItemProvider.dispose();
		if (specHierarchyChildrenItemProvider != null)
			specHierarchyChildrenItemProvider.dispose();
		if (specHierarchyRootChildrenItemProvider != null)
			specHierarchyRootChildrenItemProvider.dispose();
		if (datatypeDefinitionBinaryFileItemProvider != null)
			datatypeDefinitionBinaryFileItemProvider.dispose();
		if (datatypeDefinitionBooleanItemProvider != null)
			datatypeDefinitionBooleanItemProvider.dispose();
		if (datatypeDefinitionDocumentItemProvider != null)
			datatypeDefinitionDocumentItemProvider.dispose();
		if (datatypeDefinitionEnumerationItemProvider != null)
			datatypeDefinitionEnumerationItemProvider.dispose();
		if (datatypeDefinitionIntegerItemProvider != null)
			datatypeDefinitionIntegerItemProvider.dispose();
		if (datatypeDefinitionRealItemProvider != null)
			datatypeDefinitionRealItemProvider.dispose();
		if (datatypeDefinitionStringItemProvider != null)
			datatypeDefinitionStringItemProvider.dispose();
		if (datatypeDefinitionsItemProvider != null)
			datatypeDefinitionsItemProvider.dispose();
		if (datatypeDefinitionXmlDataItemProvider != null)
			datatypeDefinitionXmlDataItemProvider.dispose();
		if (datatypesItemProvider != null)
			datatypesItemProvider.dispose();
		if (defaultValue2ItemProvider != null)
			defaultValue2ItemProvider.dispose();
		if (defaultValue3ItemProvider != null)
			defaultValue3ItemProvider.dispose();
		if (defaultValue4ItemProvider != null)
			defaultValue4ItemProvider.dispose();
		if (attributeDefinitionSimpleDefaultValueItemProvider != null)
			attributeDefinitionSimpleDefaultValueItemProvider.dispose();
		if (attributeDefinitionEnumerationDefaultValueItemProvider != null)
			attributeDefinitionEnumerationDefaultValueItemProvider.dispose();
		if (attributeDefinitionComplexDefaultValueItemProvider != null)
			attributeDefinitionComplexDefaultValueItemProvider.dispose();
		if (attributeValueEmbeddedDocumentDefinitionItemProvider != null)
			attributeValueEmbeddedDocumentDefinitionItemProvider.dispose();
		if (attributeValueFileReferenceDefinitionItemProvider != null)
			attributeValueFileReferenceDefinitionItemProvider.dispose();
		if (attributeValueEmbeddedFileDefinitionItemProvider != null)
			attributeValueEmbeddedFileDefinitionItemProvider.dispose();
		if (attributeValueSimpleDefinitionItemProvider != null)
			attributeValueSimpleDefinitionItemProvider.dispose();
		if (attributeValueEnumerationDefinitionItemProvider != null)
			attributeValueEnumerationDefinitionItemProvider.dispose();
		if (attributeValueXmlDataDefinitionItemProvider != null)
			attributeValueXmlDataDefinitionItemProvider.dispose();
		if (documentRootItemProvider != null)
			documentRootItemProvider.dispose();
		if (embeddedValueItemProvider != null)
			embeddedValueItemProvider.dispose();
		if (enumValueItemProvider != null)
			enumValueItemProvider.dispose();
		if (objectItemProvider != null)
			objectItemProvider.dispose();
		if (propertiesItemProvider != null)
			propertiesItemProvider.dispose();
		if (specGroupRelationGroupsItemProvider != null)
			specGroupRelationGroupsItemProvider.dispose();
		if (accessPolicyRelationGroupsItemProvider != null)
			accessPolicyRelationGroupsItemProvider.dispose();
		if (relationGroupItemProvider != null)
			relationGroupItemProvider.dispose();
		if (relationTypeItemProvider != null)
			relationTypeItemProvider.dispose();
		if (rifItemProvider != null)
			rifItemProvider.dispose();
		if (sourceItemProvider != null)
			sourceItemProvider.dispose();
		if (specAttributesItemProvider != null)
			specAttributesItemProvider.dispose();
		if (rifSpecGroupsItemProvider != null)
			rifSpecGroupsItemProvider.dispose();
		if (accessPolicySpecGroupsItemProvider != null)
			accessPolicySpecGroupsItemProvider.dispose();
		if (specGroupItemProvider != null)
			specGroupItemProvider.dispose();
		if (specHierarchiesItemProvider != null)
			specHierarchiesItemProvider.dispose();
		if (rifSpecHierarchyRootsItemProvider != null)
			rifSpecHierarchyRootsItemProvider.dispose();
		if (accessPolicySpecHierarchyRootsItemProvider != null)
			accessPolicySpecHierarchyRootsItemProvider.dispose();
		if (specHierarchyRootItemProvider != null)
			specHierarchyRootItemProvider.dispose();
		if (specHierarchyItemProvider != null)
			specHierarchyItemProvider.dispose();
		if (specifiedValuesItemProvider != null)
			specifiedValuesItemProvider.dispose();
		if (specGroupSpecObjectsItemProvider != null)
			specGroupSpecObjectsItemProvider.dispose();
		if (rifSpecObjectsItemProvider != null)
			rifSpecObjectsItemProvider.dispose();
		if (accessPolicySpecObjectsItemProvider != null)
			accessPolicySpecObjectsItemProvider.dispose();
		if (specObjectItemProvider != null)
			specObjectItemProvider.dispose();
		if (rifSpecRelationsItemProvider != null)
			rifSpecRelationsItemProvider.dispose();
		if (relationGroupSpecRelationsItemProvider != null)
			relationGroupSpecRelationsItemProvider.dispose();
		if (accessPolicySpecRelationsItemProvider != null)
			accessPolicySpecRelationsItemProvider.dispose();
		if (specRelationItemProvider != null)
			specRelationItemProvider.dispose();
		if (rifSpecTypesItemProvider != null)
			rifSpecTypesItemProvider.dispose();
		if (accessPolicySpecTypesItemProvider != null)
			accessPolicySpecTypesItemProvider.dispose();
		if (specTypeItemProvider != null)
			specTypeItemProvider.dispose();
		if (targetGroupItemProvider != null)
			targetGroupItemProvider.dispose();
		if (targetItemProvider != null)
			targetItemProvider.dispose();
		if (attributeDefinitionSimpleTypeItemProvider != null)
			attributeDefinitionSimpleTypeItemProvider.dispose();
		if (specRelationTypeItemProvider != null)
			specRelationTypeItemProvider.dispose();
		if (attributeDefinitionEnumerationTypeItemProvider != null)
			attributeDefinitionEnumerationTypeItemProvider.dispose();
		if (specObjectTypeItemProvider != null)
			specObjectTypeItemProvider.dispose();
		if (specHierarchyRootTypeItemProvider != null)
			specHierarchyRootTypeItemProvider.dispose();
		if (specGroupTypeItemProvider != null)
			specGroupTypeItemProvider.dispose();
		if (attributeDefinitionComplexTypeItemProvider != null)
			attributeDefinitionComplexTypeItemProvider.dispose();
		if (specObjectValuesItemProvider != null)
			specObjectValuesItemProvider.dispose();
		if (specRelationValuesItemProvider != null)
			specRelationValuesItemProvider.dispose();
		if (specGroupValuesItemProvider != null)
			specGroupValuesItemProvider.dispose();
		if (specHierarchyRootValuesItemProvider != null)
			specHierarchyRootValuesItemProvider.dispose();
		if (attributeValueEnumerationValuesItemProvider != null)
			attributeValueEnumerationValuesItemProvider.dispose();
		if (xhtmlContentItemProvider != null)
			xhtmlContentItemProvider.dispose();
		if (attributeValueEmbeddedDocumentXhtmlContentItemProvider != null)
			attributeValueEmbeddedDocumentXhtmlContentItemProvider.dispose();
		if (xmlContentXmlContentItemProvider != null)
			xmlContentXmlContentItemProvider.dispose();
		if (attributeValueXmlDataXmlContentItemProvider != null)
			attributeValueXmlDataXmlContentItemProvider.dispose();
	}

}
