<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="erf"
    nsURI="http://era/foss/erf" nsPrefix="era.foss.erf">
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDefinition" abstract="true"
      eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DatatypeDefinition">
      <eAnnotations source="UI">
        <details key="ObservedStructuralFeature" value="coreContent:dataTypes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorShowLabel" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorRowNumber" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editorColumnSpan" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiShowLabel" lowerBound="1"
        eType="#//DatatypeDefinition">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValue" abstract="true" eSuperTypes="#//Identifiable"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeDefinition" abstract="true"
      eSuperTypes="#//Identifiable"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecElementWithUserDefinedAttributes"
      abstract="true" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//AttributeValue" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SpecType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecObject" eSuperTypes="#//SpecElementWithUserDefinedAttributes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
        upperBound="-1" eType="#//SpecRelation" eOpposite="#//SpecRelation/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
        upperBound="-1" eType="#//SpecRelation" eOpposite="#//SpecRelation/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecType" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specAttributes" upperBound="-1"
        eType="#//AttributeDefinition" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map" instanceClassName="java.util.Map"
      abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eTypeParameters name="T1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeValueSimple" eSuperTypes="#//AttributeValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="DatatypeDefinitionConstraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//AttributeDefinitionSimple"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeDefinitionInteger" eSuperTypes="#//DatatypeDefinitionSimple">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonNegative MaxGreaterThanMin"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeDefinitionSimple" abstract="true"
      eSuperTypes="#//DatatypeDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatatypeDefinitionString" eSuperTypes="#//DatatypeDefinitionSimple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        unsettable="true">
      <eAnnotations source="UI">
        <details key="Detail" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDefinitionSimple" eSuperTypes="#//AttributeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//AttributeValueSimple"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ERF">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coreContent" lowerBound="1"
        eType="#//Content" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specObjects" upperBound="-1"
        eType="#//SpecObject" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specTypes" upperBound="-1"
        eType="#//SpecType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DatatypeDefinition" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specRelations" upperBound="-1"
        eType="#//SpecRelation" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecRelation" eSuperTypes="#//SpecElementWithUserDefinedAttributes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//SpecObject" eOpposite="#//SpecObject/targets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//SpecObject" eOpposite="#//SpecObject/sources"/>
  </eClassifiers>
</ecore:EPackage>
